= Civil Networks Lua Programming Standards
:source-highlighter: highlight.js
:toc:
Civil Networks Development Team

== Overview
Civil Networks is a very large network. Writing clean, maintainable, and extendable code is the #1 priority for all of Civil Network's developers.

== Remember
Here's a list of things you need to remember when making addons for Civil Networks:

. We have Code Review, don't write code you don't want other people seeing
. We have `sv_allowdownload` disabled. In most cases, resource.AddFile won't do anything. Ask Ventz to have the content added to a content pack.

== Addon Structure
Structuring addons in a way that allows other people to follow what's going on and make good guesses about where functionality is implimented allows other developers to work better.

=== Naming Files
Files should be named with a prefix of the state followed by a single noun or verb describing what the file contains.

Prefixes to use for files:

* `sh_`: Shared Files
* `sv_`: Server Files
* `cl_`: Client Files

=== File Structure
Addon files are organised into a central folder that has the addon's name. Addons should try not to have more than one folder directly inside the lua directory.

Here's an example:
[source]
----
📂 /lua/autorun:
    📄 sh_addon_init.lua <1>
📂 /lua/my_addon: <2>
    📂 /lua/my_addon/client: <3>
        📄 cl_render.lua
        📄 cl_hud.lua
        📄 cl_net.lua
    📂 /lua/my_addon/server:
        📄 sv_net.lua
    📄 sh_config.lua
    📄 sv_config.lua <4>
----
<1> If you need a server or client specific autorun, use autorun/(client/server)/(cl/sv)_addon_init.lua
<2> This is the addon's directory, you should not create multiple folders directly inside the lua path for your addon
<3> Files that are specific to the server or client should be in folders. The only files in the root of you addon's lua folder should be
<4> Server configuration files are useful to store sensitive information. Never store API Keys in shared files unless clinets should access them.

TIP: To maintain readability (and just generaly making things easier to find), try not to encapsulate complicated addons in a small number of files. More files is usualy better, allowing for people to find things easier.

=== Global Tables & Variables

==== Avoid Global Variables
Global variables can lead to unexpected behavior, conflicts, and bugs in the Lua state. To maintain clean and maintainable code, it is recommended to minimize the use of global variables. They should only be used in specific cases, such as when creating an addon table.

If you need global data storage, consider using a dedicated addon table to encapsulate your global data. This helps prevent naming conflicts with other addons and keeps your variables organized.

Here's a bad example:
[source, lua]
----
-- These are declared as global variables, even though they're only used for one addon
RequiredPolice = 50
RequiredCitizens = 10
----

Here's a good example:
[source, lua]
----
-- Everything is encapsulated inside the MyAddon table
MyAddon = MyAddon or {}
MyAddon.Config = {}

MyAddon.Config.RequiredPolice = 50
MyAddon.Config.RequiredCitizens = 10
----

==== _G
The _G table should never be used except in very specific cirsumstances, such as detouring. Never use this without a good reason. Your code review will fail if you use _G just because you felt like it.

=== Naming Conventions

Use the following naming contentions throughout the Civil Network's codebase:

* PascalCase for addon tables (`MyAddon`, `CNAdvent`, `VOrgs3`)
* PascalCase when defining metatables (`ply:GetData()`)
* PascalCase when defining global functions (`MyAddon.Create()`, `MyAddon.NewObject()`, `MyAddon.ClassName:New()`)
* camelCase for local variables (`required`, `numRemaining`, `count`)
* camelCase for table keys (`MyAddon.required`, `CNAdvent.config`, `VOrgs3.config.numHouses`)
* camelCase for local functions (`doRefresh()`, `doCreate()`)
* camelCase when defining variables attached to entities (`ent.isSpawned`, `ent.lastOwnedBy`, `ply.isNewPlayer`)

=== Modularity
Modular addons are good addons, and writing modular code is also a good practice. For example, if you're writing a logging addon, you should let other people add logs relatively easily.

A good way of achieving this is hotloading all the files inside a directory on startup, and running their code.

Imagine a file structure like this:
[source]
----
📂 /lua/autorun:
    📄 sh_logaddon_init.lua <1>
📂 /lua/log_addon: <2>
    📂 /lua/log_addon/modules/logging: <3>
        📄 sh_whitelist.lua
        📄 sh_darkrp.lua
        📄 sh_sandbox.lua
        📄 sh_weapons.lua
        📄 sh_admins.lua
----

Upon server start, `logaddon` will load the contents of these files.

Modularity is often achieved by using metatables as builders. This allows a module file to look something like this, ignoring differences between addons:
[source, lua]
----
local module = LogAddon:NewLog()

module:SetName("Admin Logging")
module:SetCategory(Color(255, 75, 75))

module:AddHook("InitPostEntity", function()
    print("I was called :D")
end)

module:Register()
----

== Writing Code

=== Never include semicolons after lines in Lua code

Bad:
[source,lua]
----
local a = "corn";
print(a);
----

Good:
[source,lua]
----
local a = "corn"
print(a)
----

=== Use != and continue in GLua
When writing GLua code, avoid using `~=` and the `goto` statement. Prefer using the glua alternatives.

Bad:
[source,lua]
----
for k, v in player.Iterator() do
    if (v:Nick() ~= "Apple") then
        goto continue
    end

    print("HE'S HERE!!")
    ::continue::
end
----

Good:
[source,lua]
----
for k, v in player.Iterator() do
    if (v:Nick() != "Apple") then
        continue
    end

    print("HE'S HERE!!")
end
----

=== Avoid defining functions with colons unless self is required
When defining a member table function for your addon or whatever, avoid using the colon unless you are using `self` in your function.

Bad:
[source,lua]
----
function MyAddon:DoThings()
    print("Did the thing")
end
----

Good:
[source,lua]
----
function MyAddon.DoThings()
    print("Did the things")
end

function MyAddon:CreateObject()
    self.objects = self.objects + 1 <1>
    print("Did the things")
end
----
<1> This is allowed because we use self in this function.

=== Always define metatable meta functions with colons
When defining a metatable function on anything, including players and entities, use colons.

Bad:
[source,lua]
----
function plyMeta.BanForAdminAbuse()

end
----

Good:
[source,lua]
----
function plyMeta:BanForAdminAbuse()

end
----

=== Write loops using (k, v), (i, j), (a, b), ...
When writing loops in your code, always use the following order of loops:

. k, v
. i, j
. a, b
. m, n
. o, p

WARNING: Using nested loops is discouraged, only use nested loops over you really need to. If you weite enough nested loops to require more options then the ones provided above, please contact your local head developer and tell them you're resigning.

Bad:
[source,lua]
----
for v, k in ipairs(tab) do

end

for i, k in ipairs(tab) do
    for k, v in ipairs(v) do

    end
end
----

Good:
[source,lua]
----
for k, v in ipairs(tab) do

end

for k, v in ipairs(tab) do
    for i, j in ipairs(v) do
        print(k, i)
    end
end
----

==== Loop iterator variables with wierd values
If the value of your loop iterator variable isn't immediately obveous or you're writing crazy nested loops, give the variables good names.

=== Include a comma after the last member of an inline defined table
When defining tables in Lua, always include the trailing comma. This includes inline defined tables.

Bad:
[source,lua]
----
local players = {1, 2, 3}
----

Good:
[source,lua]
----
local players = {1, 2, 3, 4,}
----

=== Avoid variable shorthand
Avoid using shorthand or abreviated names for variables unless the name is common and very obveous.

Bad:
[source,lua]
----
local pTbl = {}
local tells = {}
local x = 5
local y = 10
----

Good:
[source,lua]
----
local playerTable = {}
local playersToTell = {}
local numPlayersOnline = 5
local numPlayersReserved = 10
----

=== Prefer positive checks
When writing an expression for a boolean condition, tend to use positive checks rather than negative checks where possible, E.G prefer `if (myValue) then else end` over `if (not myValue) then else end`

Bad:
[source,lua]
----
if (not myValue) then
    return
else
    print("Yipee!")
end
----

Good:
[source,lua]
----
-- you should use a guard clause here anyway
if (myValue) then
    print("Yipee!")
else
    return
end
----

=== Guard Clauses
Guard clauses allow you to exit out of a function early, and are incredibly useful tools for checking lots of information without needing to increast indentation for the rest of your code.

If you have many guard clauses one-after another that all result in the same thing happening (for example returning), just combine them all into one if-statement.

Bad:
[source,lua]
----
if (myValue and otherValue and otherValue == "apple") then
    print("i did a thing")
else
    return
end

funciton doThing(val1, val2, val2)
    if (val1 != "okie") then
        return
    end
    if (val2 != "dokie") then
        return
    end
    if (val3 != "artichoke") then
        return
    end

    print("did a thing!")
end
----

Good:
[source,lua]
----
if (not myValue or not otherValue or not otherValue == "apple") then
    return
end

print("I did a thing")

funciton doThing(val1, val2, val2)
    if (val1 != "okie" or val2 != "dokie" or val3 != "artichoke") then
        return
    end

    print("did a thing!")
end
----

=== Indentation
All code should be properly indented with tabs the width of 4 charaters. Only indented code should be avoided, which you may have heard called the arro anti-pattern.

For example, never do this:
[source,lua]
----
if (thing) then
    if (otherThing) then
        if (otherThingAndOtherThing) then
            if (x) then
                if (y) then
                    print("okie")
                end
            end
        end
    end
end
----

=== If statements & loops
An if statement must never be written on one line. For example a simple if statement to early out of a function must be written on three lines:
[source,lua]
----
if (true) then
    return
end
----

If statements, loops, function calls and object constructors must be written with braces, with no spaces padding the inside. If statements and while loops must also have spaces padding the outer braces, for example:
[source, lua]
----
local a = 0
while (a < 10) do
	a = a + 1
end
----

=== Magic Numbers
Avoid magic numbers, or numbers that exist in the codebase with no explanation of where they came from. For example, if you're doing a calculation like:

`local repToTake = math.clamp(rep*343/2, 43)`

Consider adding comments that explain where the random nubers come from, or put the numbers into variables with good names.

== Networking & Security
When creating addons which allow clients to send net messages to the server, it is vital to carefully consider all security implications and potential attack vectors for exploiters. A simple example would be a net message allowing a superadmin to perform an administration or config task on the server. Net messages such as these must always check the player is allowed to use the message. If a client attempts to use a net message which they should not have access to, you have the choice whether to send a notification explaining why the net message can't be used, or to silently fail if you believe the client should not know.

=== Never trust the client
When writing a server net message callback, it is vital to remember that the client can never be trusted. You may expect some certain data to be written to the message by the client, and it may be easy to assume this information will be what you expect, however it is important to know that a client can potentially be writing whatever they want to a net message, be that on purpose or accidental. When receiving data from a client you should always validate every aspect of the data, including but not limited to:

* Does the data exist
* Is the data valid (is the value allowed)
* Is the data within the expected range
* If the data too large
* Is the value possible


==== Targets
When accepting a network message that sends an entity, be sure to check if the entity is the right type. Also consider checking if the player is close enough to trigger the message normaly.

==== Notifications
For net messages which run in response to user input such as a UI button, entity use etc, a notification should be displayed to the player. If the operation is successful, you should notify them of the success if it is not already apparent to them, if the operation fails a reason for the failure should be displayed unless you believe that could be a security risk.

== Saving Data

=== Player Data
All player data which is saved or loaded such as levels, stats and other permanent data must be saved to the MySQL database. An exception can be made if the data is **very** unimportant, temporary or otherwise can't be stored in the database properly.

=== Map Data
Persistent map data for example perma props or saved entities must be saved in a data file inside the servers data folder. When saving map data, the data must be saved in a folder or file with the name of the map it was saved for. This is to allow us to migrate data to new map versions by changing the name of the file, and to save different data on different maps.

Example of good paths for map data:

* data/addon_name/rp_mapname_v1.txt
* data/addon_name/rp_mapname_v1/file1.txt

=== SQL Queries
Every SQL query will contribute to our server bandwidth bill, which can easily become out of hand. SQL queries should be done as little as possible in order to reduce bandwidth usage, only make SQL queries when fetching initial data for something or when updating information. If data is updated very often, try reducing the amount of queries done by deferring any saving to a later date, perhaps saving only once every few minutes rather than every time the data is changed. Finally, ensure you are only writing data to SQL that has changed, and avoid updating any values which you know have not changed.

== Documenting Code

=== Comments
Comments should be written to explain sections of code if the purpose or behavior of the code might not be immediately obvious to someone else who is reading it. Prefer to use – to begin comments rather than //. Comments can be lengthy, however, you should avoid writing excessive amounts of comments all over code unless it is absolutely necessary.

Usually, good variable names can behave as comments themselves simply by making the purpose of a variable immediately clear and apparent. Every time you write a comment, ask yourself first: can I avoid needing this comment by simply giving some variables better names?